# Generated by Django 2.1.3 on 2019-01-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_cateory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cateory',
            new_name='category',
        ),
    ]
